### ISSUE TITLE
coins not reached wallet

### ISSUE THREAD

**Issue by marcusnoke** [electroneum/electroneum-pool#45]
Hi,,I have mined on the  eupool  and it shows on the web page i have been paid...transaction no   2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db
however the funds never reached my wallet,yet it has done from other pools..
when i click the transaction number on web page it says   
can't get   tx2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db
the wallet number on pool is correct and I've refreshed wallet several  times..
hope you can help
cheers
marcus

**Comment by alant12345** [comment]
i got the same issue 65ETN was not payout and show success in the europool website.

2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db

https://blockexplorer.electroneum.com/tx/9d716dedcbe83c6bb4d55c6f44cb2c22d5d64d823509d21054589ea7c33dd000
<img width="1208" alt="screen shot 2017-11-25 at 4 01 50 am" src="https://user-images.githubusercontent.com/33448748/33222864-79e10c2a-d195-11e7-8534-225fb3594043.png">

**Comment by privacybtc** [comment]
Hi, I faced this problem and fixed it , problem in ur wallet
You must re build ur wallet by
get all ur wallet info saved : View key: secret: spendkey public: spendkey Recover Acsess
Then delete ur wallet file or move it away
open ur windows CMD
CD to ur wallet directory
then run the wallet by this command

electroneum-wallet-cli.exe --generate-from-keys CHANGENAME.etn

use new wallet name.etn
then put ur saved info
ur wallet will be rebuild and u will got ur money back.
I hope This problem must be fixed in next coins' blockchain update

**Comment by alant12345** [comment]
Thanks for your feedback however, the regenerate wallet and import is not working. The 65 etn payout transaction still not appear.

you may see the transaction display during the refresh process.

Starting refresh...
Height 14485, transaction <dfd7418c195b2a2ad725549c51759bd0550fe2f343bb9a8d2366eade0002e8dd>, received 2.00
Height 15471, transaction <d1905d31cb58a22edd0bc76e5974240d4dbc58fad18fa2a1595902081923df2c>, received 2.00
Height 15820, transaction <d4ff2e706055dd77b9ac37795220860ce643d0e92f20e8a38cfbd2b08c57585e>, received 2.00
Height 15820, transaction <d4ff2e706055dd77b9ac37795220860ce643d0e92f20e8a38cfbd2b08c57585e>, received 20.00
Height 16918, transaction <a5a4246f629ea238debecbca17cd7d124b008c65881dc78c581bbacbc03efa45>, received 2.00
Height 18086, transaction <4ad77ab967f85260d218188b60b28a652ef6d530e4c7d2071d775f97239a8abb>, received 2.00
Height 21198, transaction <2eacd4e3bb7919442d141167b2b8e21446c08a7d07ef0f4a65c14d5b2042ec3e>, received 20.00
Height 21910, transaction <727fbc87357dab85ae64746960be53cff7364da533b99657e02e4b7e36a3d7ab>, received 2.00
Height 21914, transaction <8d2c8cca8dc4b0c11b6443714f3904db472e903edd8742286d3e0df1bc2c426e>, received 2.00
Height 22562, transaction <6b13eff055f9d9ee59b21fc3397b02bc09b48e85cc94002584f90aeb86deb37d>, received 2.00
Height 24301, transaction <1e48345730d366b707ba472fd00294a68d8854bf66c292f6367ffddb6198c0c3>, received 5.00
Height 27224, transaction <88e08c4fe980e7982bf8ab2555ef2d9e70bfaa3f39b1976d37f7ba8d0c65c8f9>, received 10.00
Height 29183, transaction <faa0201637c8e8963f65ec48eb41c7f3ec07594bb37abe7648599f5327a8d911>, received 10.00
Height 31662, transaction <b9ada238c6b29f3885076f4fbcd17104661a2ab7e9a037f5184f203d14792bf7>, received 9.00
Height 33417, transaction <5787edc8ce6b090d0b4eb4a7a02b504d92dd9021af5ff4be504aa8bed94767f6>, received 10.00
Height 34055, transaction <5fb6e07cbd8ad8cd15e23aca4e74402383555d65f7096dce7260f052c4f27675>, received 10.00
Height 37019, transaction <bba1da23bbcc3ba3b61815d530abea90bc0371d83a17c6e426751a83f6841992>, received 10.00
Height 39075, transaction <0b46ec974810442e8eb9d37c073eedb197dd26969ed504b2b379d07b7d762d7b>, received 10.00
Height 40867, transaction <99cfe80d7cbf0135af240093d15ed9b2e5a87c6b965b3c89463e0c15f33efdb7>, received 10.00
Height 43085, transaction <53da8eaae3c411a9328d534ef66f66c0623d4fa13050125c4946b99ca893ff9b>, received 10.00
Height 49203, transaction <6de284229693fbb4eed76974c65303048b4cb00b82e8d14bb132f0c1cfca25c9>, received 10.00
Height 54305, transaction <026d50b87a010c1c4ef2d33b5fba54111fdc609c2e1e4ac77e3c959abc802953>, received 10.00
Refresh done, blocks received: 55773                            
Balance: 170.00, unlocked balance: 170.00

I confirmed that the problem is the europool doesn’t have sufficient coins to payout and cause the transaction failed. I really wish someone from official etn euro pool rectify this problem and give me back the coin :(

this is the missing transaction id.
9d716dedcbe83c6bb4d55c6f44cb2c22d5d64d823509d21054589ea7c33dd000

this is the transaction explorer link https://blockexplorer.electroneum.com/tx/9d716dedcbe83c6bb4d55c6f44cb2c22d5d64d823509d21054589ea7c33dd000

**Comment by Shadooww** [comment]
Hi, I got the same issue with 61ETN
Transaction 7159aa98c243a3c8ac903435e438243362d5be1f1952b4eb6d3c9704ddb18137

https://blockexplorer.electroneum.com/tx/7159aa98c243a3c8ac903435e438243362d5be1f1952b4eb6d3c9704ddb18137

how to solve the problem?

**Comment by privacybtc** [comment]
Rebuild the wallet by the way in my post.
________________________________

**Comment by alant12345** [comment]
Rebuild is not working, I do send support ticket to electronuem team but required to wait few weeks. If the rebuild is working kindly update here. Thank You

**Comment by marcusnoke** [comment]
How is rebuilding the wallet going to work when the transaction doesn't seem to be in the blockchain?
when I click on the transaction id  involved (2e408a62cd7bea88e2f3fb438e48aa0594d233867e4181c3cc0549bdb2c7a2db) it doesn't go anywhere,as I explained in the first message,,all my other transaction id's  list the blocks involved when you click on them..

**Comment by alant12345** [comment]
What you say is correct. I suspect is the pool insufficient etn to perform payout but system still shows as success. The ETN should be still inside the pool.
