### ISSUE TITLE
npm update fails on node-gyp rebuild

### ISSUE THREAD

**Issue by Grimm2017** [electroneum/electroneum-pool#59]
Failed at the cryptonote-util@0.0.3 install script 'node-gyp rebuild'

**Comment by rvrsh3ll** [comment]
Same issu
[npm-debug.log](https://github.com/electroneum/electroneum-pool/files/1515886/npm-debug.log)
e here. Please advise.
Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by rvrsh3ll** [comment]
You can use 'apt install nodejs=0.10*' and then 'npm update'.
It helped me solve the problem. 👍

**Comment by Grimm2017** [comment]
I tried what you suggested and now npm update doesn't so anything.  

I already had nodejs 0.10.48 installed.

**Comment by electroneumRepo** [comment]
Make sure you have installed all dependencies,

Have you installed boost? This is required for the cryptonote-util module.
What OS are you using?
What version of nodejs are you using?

**Comment by Mvanmierlo** [comment]
Same issue here on  Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64) 
```
root@minernet:~/pool# npm update

> bignum@0.12.5 install /root/pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
cryptonote-pool@0.0.1 /root/pool
├── cryptonote-util@0.0.3  (git://github.com/Snipa22/node-cryptonote-util.git#49d6ec72d499bba9144d4a3ebdf4b62a4262aa8a)
└── multi-hashing@0.0.9  (git://github.com/zone117x/node-multi-hashing.git#73996fe77104108f2d66ef750b3e1bce42e4d8f0)

npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pool/npm-debug.log

```

**Comment by Mvanmierlo** [comment]
Is the nodeJS version v0.10.48 explicit ? I have googled and tried numerous solutions to get this installed but this is an old (2016) version and my Ubuntu package manager only lets me install version v4.2.6.

Even : 
curl -sL https://deb.nodesource.com/setup_0.10 |  sudo -E bash -
sudo apt-get install -y nodejs

Did not work. 
No idea to fix this.

**Comment by electroneumRepo** [comment]
> Is the nodeJS version v0.10.48 explicit ?

Yes, you must have 0.10.48 otherwise some of the modules will NOT work.

You can install different versions of nodejs by first install [Node Version Manager](https://github.com/creationix/nvm). This makes it really easy to install old version and use multiple versions if required.

Once installed, you can install 0.10.48 by typing the command `nvm install v0.10.48`. You may then have to type `nvm use 0.10.48` before it changes to that version.

I've updated the README file so that this is a little clearer

**Comment by Mvanmierlo** [comment]
I went back to a clean install, again succesfully compiled electroneum installed NVM and 0.10.48 
I still get errors and have the feeling I am missing a dependency here.
But now I get this :

`root@minernet:~/pool# npm update
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine deep-extend@0.4.2: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.48","npm":"2.15.1"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.48","npm":"2.15.1"})

> bignum@0.12.5 install /root/pool/node_modules/base58-native/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp: Permission denied

> bignum@0.12.5 install /root/pool/node_modules/bignum
> node-pre-gyp install --fallback-to-build

sh: 1: node-pre-gyp: Permission denied
/
> cryptonote-util@0.0.3 install /root/pool/node_modules/cryptonote-util
> node-gyp rebuild

sh: 1: node-gyp: Permission denied

> multi-hashing@0.0.9 install /root/pool/node_modules/multi-hashing
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/root/.nvm/v0.10.48/bin/node" "/root/.nvm/v0.10.48/bin/npm" "update"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bignum
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pool/npm-debug.log
root@minernet:~/pool#
`

**Comment by electroneumRepo** [comment]
@Mvanmierlo You are running the npm update command as root.

Under no circumstances should you run it as root.

I would suggest for you to create a new user and then try once again.

**Comment by Mvanmierlo** [comment]
Thanks ! I worked in a sudo i session so exit this.

Got a lot of warnings but seems to do the job.
Thanks for the support much appreciated !
